### ISSUE TITLE
Use Piwik as analytics tool

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#17]

**Comment by althio** [comment]
I say this is important, particularly in light of the effort made with a user survey, user UI/UX improvement...
Maybe we don't know how to use this data yet, but we should start collecting as soon as possible.
We are doing it on LearnOSM, HOT website, INAsafe, we should do it on Tasking Manager.
We should figure out if we need a special config or trick regarding the instances.

And higher priority from my point of view.

cc: @heatherleson @bgirardot @pierzen @mataharimhairi

**Comment by ethan-nelson** [comment]
I think the first thing is for a piwik admin to create a site profile for the TM, if one does not already exist. Then we can maybe integrate variables pertaining to the piwik configuration in the .ini files, with the HOT live TM site set to use HOT's version of piwik. The method would ideally allow someone running piwik on their own instance to add their own configuration information (site id, tracker url, etc.).

**Comment by dodobas** [comment]
This is the code for piwik tracking
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDoNotTrack", true]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//piwik.hotosm.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 7]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//piwik.hotosm.org/piwik.php?idsite=7" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->

```

**Comment by bgirardot** [comment]
This was completed!
