### ISSUE TITLE
More user links

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#300]
The user names may appear at different locations in the UI. Let's add "to profile" links there.

**Comment by pyrog** [comment]
Username should be clickable also in the projects list :wink: 
![user name in projects list](https://cloud.githubusercontent.com/assets/2158081/5627962/a24eac50-95a0-11e4-9b13-58aef8c4abcb.png)

**Comment by ethan-nelson** [comment]
@pyrog i am out of town for a conference this week, so having to do edit in browser. Are you able to test a quick fix for this? https://github.com/ethan-nelson/osm-tasking-manager2/commit/12bda159f8cc8cd7313f176c585060300474949c

**Comment by pyrog** [comment]
:+1: fine, thanks
