### ISSUE TITLE
User profile problem (nickname vs uid) creates broken links and incompatibilities

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager2#325]
The http://tasks.hotosm.org/users page refers to a user by his OSM nickname instead of the uid. This creates problem when a user change his nickname.

For example, in the Users list, we have nickname rwst. 
this links to http://tasks.hotosm.org/user/rwst

This second page links to http://tasks.hotosm.org/user/1833571/project_manager and http://tasks.hotosm.org/user/1833571/admin. But not possible to link as http://tasks.hotosm.org/user/1833571. 

The excellent User profile page provides a summary of a user experience witht the Task Manager. This can be very useful to follow contributors. But two important links are broken when  contributor modifies his nickname.

1. The OSM user profile url http://www.openstreetmap.org/api/0.6/user/rwst
should be http://www.openstreetmap.org/api/0.6/user/1833571

2. The Overpass Query url using the user parameter should be replaced by uid parameter.

**Comment by pgiraud** [comment]
The username is changed in the tasking manager as soon as the user page is displayed if the "displayed name" has been changed in OSM.
