### ISSUE TITLE
User Profile page : How long the user contributes to OSM

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager2#326]
The OSM api user profile provides the date of creation of an OSM account. Adding this information at the top of the User profile, would give us an indication of the user experience with OSM.

**Comment by ethan-nelson** [comment]
This can be closed via #581. @althio maybe open a new ticket for your comments specifically to expand the ''tiles completed'' section of the user profile.

**Comment by althio** [comment]
@ethan-nelson 
> @althio maybe open a new ticket for your comments specifically to expand the ''tiles completed'' section of the user profile.

Thanks for the pointer, done at #613.
