### ISSUE TITLE
link to overpassturbo for an individual task

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-tasking-manager2#376]
for example, http://tasks.hotosm.org/project/599#task/640

**Comment by ethan-nelson** [comment]
Is this to see all the objects in the task box, or ones contributed specifically by those that worked on (i.e. locked) the task in the tasking manager?

**Comment by ethan-nelson** [comment]
Went with the latter as it makes more sense.

**Comment by ethan-nelson** [comment]
Implemented via #543.
