### ISSUE TITLE
Change "changeset comment" to "commit message" to match iD labels

### ISSUE THREAD

**Issue by kevindobbs** [hotosm/osm-tasking-manager2#422]
The term in the OSM-TM Instructions, i.e. the words “changeset comment,” should match those I the iD editor, which read “commit message.”  Especially for beginners it is important that the terms agree. It should match iD because JOSM users can probably figure it out.

**Comment by ethan-nelson** [comment]
iD has now changed the label to "changeset comment" via https://github.com/openstreetmap/iD/issues/2600. This issue can be closed now as the confusion should be eliminated.

**Comment by pgiraud** [comment]
Indeed. Closing. Thanks @ethan-nelson for asking for this change in iD.
