### ISSUE TITLE
curious display order glitch (very limited and minor)

### ISSUE THREAD

**Issue by danbjoseph** [hotosm/osm-tasking-manager2#425]
The question glyphicons next to 'Entities to Map' and 'Changeset Comments' appear over the task nav bar, but not the red page nav, as you scroll down when observed in Chrome v38.0.2125.111 on a MacBook Pro (Retina, 15-inch, Late 2013) but curiously enough, the problem disappears when the browser window is moved over and viewed on a Samsung s27c350 monitor. Doesn't seem to happen in Firefox 33.0.2

![screen shot 2014-10-31 at 4 25 44 pm](https://cloud.githubusercontent.com/assets/4806884/4857899/8170737c-60d7-11e4-897a-dd8ac9129021.png)

**Comment by ethan-nelson** [comment]
Have you experienced this as of late in Chrome?

**Comment by danbjoseph** [comment]
On the same machine as before, I no longer see this. With Chrome now at v50.0.2661.86
