### ISSUE TITLE
database should perhaps not have a completely generic name

### ISSUE THREAD

**Issue by rkiddy** [hotosm/osm-tasking-manager2#430]
Looking at the README, I see:
> First create a database user/role named `www-data`

Hm. Because nobody else would use that name? :-)

Perhaps www-osm-data? Or even www-hottasking-data, yes?

I have other postgres databases on my machine. This is probably not an unusual circumstance.

**Comment by skalca** [comment]
Does this only need to be changed in the README file? If so, I can change it. Let me know.

**Comment by rkiddy** [comment]
No, the name of the database, as it gets created and accessed, should be changed. The documentation has nothing to do with it. Should every application that uses a database and talks to the web call its database "www-data"?

**Comment by skalca** [comment]
I might be missing something, but are you (@rkiddy) talking about changing the __name__ of the database (eg. osmtm) or the __user__ that accesses that database (eg. www-data)?

**Comment by pgiraud** [comment]
Hi @rkiddy.
It's really a matter of documentation since you can create the database with the name you want and with the user you want.
See the `local.ini` file in which you have to tell the connection uri to the database.
Maybe we should document that using a notation like `<username>`, `<dbname>`, etc...

**Comment by skalca** [comment]
I would use both. For an inexperienced users (like I am) it was nice just to copy-paste code from README file and be on my way - it worked out of the box.

**Comment by pgiraud** [comment]
So unless someone proposes a better way to document this. I will mark this as wontfix.

**Comment by skalca** [comment]
Leave it open for a few days. I will try something tomorrow and make a pull request.

**Comment by rkiddy** [comment]
Jeez. Sorry for the noise. I obviously mis-read something. :-(
