### ISSUE TITLE
Random task should not assign validation task

### ISSUE THREAD

**Issue by rkiddy** [hotosm/osm-tasking-manager2#446]
As per a discussion on the HOT mailing list, it seems that when one hits the 'Take a task at random' button, one may get a square to be validated. From one of the e-mails:

>> We think that the likely scenario is - When all squares of a
>> project are either complete or locked by another mapper, Tasking
>> Manager will allocate you a square to validate - if you are
>> extremely new to the system you probably will not realise what
>> has happened and will look round the square & then add a brief
>> comment before marking the square as done. Having spoken at
>> several mapathons, and listened to other mappers giving guidance
>> I know that; a/. you can't say everything before letting someone
>> start, & b/. even if you did they probably wouldn't remember it
>> all anyway.
>>

**Comment by skalca** [comment]
This can't happen according to my testing. This issue can be closed.
