### ISSUE TITLE
stats show 99% even if project is completely done

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#457]
See front page.

**Comment by Scare1** [comment]
This is still an issue, noticeable on the Stats graph of a project (ie: http://tasks.hotosm.org/project/1830# ).  When all tiles are marked and showing as done, the graph still shows "Done 99%".  I'm not sure the graph quite reaches the 100% line either.

http://tasks.hotosm.org/ shows the same task correctly as "100%".
