### ISSUE TITLE
Show the release version

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#458]
The current deployed version should be visible in the interface. See iD editor as an example.
This should be as automatic as possible.

**Comment by pyrog** [comment]
found 2 packages:
 1. https://github.com/urga/versionfromgit
 1.  https://github.com/mikebryant/python-gitversion

For the first, I don't know how to install/add it to osmtm and in which ```__init__.py``` I should add 
```python
from versionfromgit import versions_from_git

__version__ = versions_from_git(tag_prefix="v")['version']
del versions_from_git
```

I suggest to add it at the end of about.mako:
```python
      <h3>Version</h3>
      <p> ${"v 2.1.1 build 474-981fc48"}
      </p>
```

![osmtm version](https://cloud.githubusercontent.com/assets/2158081/5654934/92b3ca0e-96c8-11e4-9d42-7245b82032d3.png)

**Comment by pgiraud** [comment]
The second one seem to be available on pypi:
https://pypi.python.org/pypi/gitversion/2.1.3

**Comment by pyrog** [comment]
In fact I have the same? problem. I can install gitversion but how to get ```__version__``` or ```version``` from about.mako ?

I'am not fluent with packages, modules… I learn from http://sametmax.com/les-imports-en-python/ but what is the top level in this project ?
* It seem that this is ```osmtm``` (can't import a package name ```osm-tasking-manager2```). Right ?<br/>But ```version.py``` seem to be beyond the top level.

Which ```import xxxx``` or ```from xxxx import``` should I use in ```project.py``` that call ```about.mako``` ?

See pyrog/osm-tasking-manager2@357db3c5b4b2166b86216108471e7d965745289f (please, don't take care of .gitmodules and versionfromgit. They shouldn't be in this commit)

**Comment by pyrog** [comment]
> Any idea ?

**rewritable_git_version** rewrite version.py :laughing:
So we should use instead **determine_git_version** :wink: 

In osmtm/version.py
```python
from gitversion import determine_git_version
__VERSION__ = determine_git_version(__file__)
```
