### ISSUE TITLE
Error: random task should have returned a task ID but did not

### ISSUE THREAD

**Issue by jakub-** [hotosm/osm-tasking-manager2#475]
This happens when clicking "Take a task at random" on a project that has been completed, for example http://tasks.hotosm.org/project/753. If this error is desired, the message could perhaps be slightly improved to read, for instance, "All tasks have been completed".

However, it seems like if all the tasks had been completed, the user should still be encouraged to verify the existing work so the "take a task at random" should still succeed.

This might be an easy task for a new contributor.

**Comment by skalca** [comment]
When the message "Error: random task should have returned a task ID but did not" is shown, it is shown on the **green** background, but the message says **"error"**. 

Is it only me, or does this annoy someone else also?

**Comment by pgiraud** [comment]
Fixed with #603.
