### ISSUE TITLE
Useful Improvements from Ruby Activation (Wish List) - Archived Projects

### ISSUE THREAD

**Issue by MarkCupitt** [hotosm/osm-tasking-manager2#485]
An activation often require sthe creation of projects in advance pending imagery being made available.

Often the project changes for many reasons, track changes, imagery has significant cloud cover, poor mapping response, etc

Currently there is no way to change the polys selected for mapping. 

What I do now, is Archive the images. Problem is, I see these and they are annoying.

Simple Fix, add a "Show Archived Projects" Check Box beside the "Your Projects" Check Box and default to Archived Tasks NOT being shown

**Comment by ethan-nelson** [comment]
Both items in your simple fix have now been added in #772
