### ISSUE TITLE
add links for tms in josm

### ISSUE THREAD

**Issue by dex2000** [hotosm/osm-tasking-manager2#506]
the implementation of changing tms in josm is a little bit tricky, 
i remember that in hotosm1 was an link to get the tms per click and without any other interaction.

steps to reproduce:
http://tasks.hotosm.org/project/805#task/247 i have to copy the tms-link (after ack the terms of use) put it into josm to the sat-overlays (and additionally it doesnt work here...)

**Comment by bgirardot** [comment]
Either I don't understand something with this one or it has been fixed, but I can't reproduce it. The imagery loads fine for me in JOSM from the Tasking Manger "Edit with JOSM" button.

Granted there is no imagery for the example task square given, but two task squares over everything seems to be working fine:

http://tasks.hotosm.org/project/805#task/203

I suggest this one gets clarified or closed as I think it works as intended.

**Comment by dex2000** [comment]
thx for testing, looks like that "my problem" is fixed.
