### ISSUE TITLE
German Translation needs amendment

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/osm-tasking-manager2#508]
Hi,  whilst translating a section of LearnOSM, @michael63-osm has commented:  

"While thus having a close look at the German interface of the TM I found that there are a number of severe errors. The worst is that the 'Unlock' button now reads 'Öffnen' which means 'open' - pretty much the opposite of what it does. Of course if you unlock a lock then it is open. Apart from that large parts are still untranslated. I will figure out to whom I can address these issues and thus open a second localization activity... "

**Comment by pyrog** [comment]
> Localisation (for all languages) is progress here at #445 & #502. After this work more strings will be available for translation in all languages.

The work is finished since Jan 2, 2015 :smile: 
See 5b32b47b0c2a2511758ffb8cae06f42912cdcf7e

Could you ask to the board to install this code (and others) in the dev server?
Then translators could work in [Transifex](https://www.transifex.com/projects/p/osm-tasking-manager2/) :wink:

**Comment by althio** [comment]
Indeed it should now fixed via #521, but not deployed yet.

@pgiraud @dodobas 
If the code is pushed to dev instance, will it trigger Transifex to propose the new strings for translation?

**Comment by pgiraud** [comment]
Should be fixed now.
