### ISSUE TITLE
Markdown Quick Reference is not translated (and up to date)

### ISSUE THREAD

**Issue by pyrog** [hotosm/osm-tasking-manager2#516]
- Need translations
- Some GitHub MarkDown flavor work but are don't explain on the Quick Reference
  - Pictures
  - Sublists
  - Headers

As there is not enough space in the quick reference, we could use tabs (like in GitHub):
![markdown examples with tabs](https://cloud.githubusercontent.com/assets/2158081/5588885/8e74c800-9112-11e4-83c8-5df390242717.png)

**Comment by ethan-nelson** [comment]
This has now been added in #907.
