### ISSUE TITLE
Send notifciation to task validator if a task is later invalidated

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-tasking-manager2#547]
Use Case: I validate a task square and later someone comes along and invalidates the same task square, I should be notified that task square got invalidated so I can see why and learn. 

Basically, we just need to check if the task is validated and if yes include the validator in the same message process that sends a notice to the person who marked the task done.

This actually just happened to me, luckily the person who marked the task done asked me about it so I look into it. (There was no reason to invalidate it by the way ;)

**Comment by althio** [comment]
related to #245  and #152 

Considering the following scenario:

userA marks as done
userB validates
userC invalidates the task -> a message is sent to userA. **Request: send also to userB.**
userD marks the task as done
nobody validates
userE invalidates the task -> a message is sent to userD.

**Comment by pierzen** [comment]
We should be careful to not be "spam like". A validator should have the option to receive or not receive these messages the same way we do when we went to follow wiki page modifications.

**Comment by althio** [comment]
@pierzen 
> We should be careful to not be "spam like". A validator should have the option to receive or not receive these messages the same way we do when we went to follow wiki page modifications.

This is mostly addressed by request #346.

My opinion is that we are far from spam with internal TM messages to 1 or 2 users. Today userA gets the notification and cannot opt-out. I wonder if it is actually a nuisance.
