### ISSUE TITLE
Get the exact date of activity tracking for each tile

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager2#550]
Basically I would need to get at leat the date of creation anc achievement of a TM job. Would be easy if eg in Marked as done it was not displayed as x days or months ago but with the exact date.

**Comment by bgirardot** [comment]
@severinmenard I am not sure if it helps you or not, but in the TM2 right now, if you hold your mouse courser over the "about 2 months ago" or other message like that on a task event, it will tell you the date/time of the event.

**Comment by severinmenard** [comment]
Oh yes, it definitely helps, thanks for the tip

**Comment by pgiraud** [comment]
@severinmenard can we close the issue?

**Comment by severinmenard** [comment]
yes

**Comment by severinmenard** [comment]
yes
