### ISSUE TITLE
Duplicated words

### ISSUE THREAD

**Issue by tassia** [hotosm/osm-tasking-manager2#560]
The words "of elements" appears twice in the string "The list of elements of elements we ask you to map". In transifex, it is the string #113.
Thanks!

**Comment by skalca** [comment]
I am not quite familiar with the whole 'locale' thingy, so I need to ask/clear a few things:

1. That string appears in the **project.instructions.mako** file, but it only references the language file. So there is no need to change *that* particular string.
2. Also it would not be suitable to change all language files.
3. Can we only add an **english** "translation" to the **english** language file **locale/en/LC_MESSAGES/osmtm.po**, like this:

> #: osmtm/templates/project.instructions.mako:13
> msgid "The list of elements of elements we ask you to map"
> msgstr "The list of elements we ask you to map"

Would that work?

**Comment by skalca** [comment]
Yup, I checked. That works. Only the en language file must be compiled again (eg. compile_catalog) and translation must be made in transifex service. I cannot do it, because I do not have sufficient privileges.

Could @pgiraud or @dodobas take a quick look at that?

**Comment by ethan-nelson** [comment]
That's a good temporary fix. I think at some point it would be best to change the string in the actual project.instructions.mako file, probably at a time when someone is about to rerun generation of all the .po files. That way, all the translations aren't broken since they cannot find the proper string.

**Comment by pgiraud** [comment]
Ah crap. I should have read @ethan-nelson and @skalca comments more carefully.
I merged @bgirardot pull request. So the languages will be broken. Sorry for the inconvenience.
