### ISSUE TITLE
Deleted Status

### ISSUE THREAD

**Issue by MarkCupitt** [hotosm/osm-tasking-manager2#562]
There needs to be a deleted status in addition to Archived items. 

Currently Archived Items display and clutter the task list

A deleted status meant that the Project should never be returned back to the main display. It could be maintained in the db for historical purposes, or dropped form the db.

The archive functionality should be changed to have it NOT display on the main Project List. But it should display when the Project Manger checks Show My Tasks

This will clean up a lot of unwanted tasks on the main list. I cannot find my own jobs sometimes if I cannot remember the numbers and the "Show my Projects" check box works sporadically.

**Comment by pierzen** [comment]
This question is related to the Main Page Mockup revision. There could be also on the Main page an option to select either archived or published jobs.

As many have expressd, It is becoming more and more a problem for the Activations and other projects (Missing Maps, training, national groups) to share space on the Main page and each express his priorities.

**Comment by ethan-nelson** [comment]
We probably don't want to drop old projects from the database, especially if we start relying on contribution stats specifically in relation to validation, etc. How are archived items determined right now? If a job is completed is it archived? Are there other situations where one is archived? We could focus on displaying only non-archived jobs (with the option to add them), and treat archive as sort of a quasi-delete.

**Comment by bgirardot** [comment]
Archived items are no longer displayed unless the "include archived" checkbox is selected, please reopen this or start a new issue if there still need to be changes to archived project handling.
