### ISSUE TITLE
Error occured accessing task

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager2#563]
A contributor reported on the HOT list that an error occured accessing some individual tasks, while for other it is working. Selecting a square, the following message is showed.
'an error occured'.
see http://tasks.hotosm.org/project/591#task/122 and http://tasks.hotosm.org/project/591#task/136 

Note that I can access other tasks:
See http://tasks.hotosm.org/project/591#task/59

It was possible with many trials to have this problem with various tasks.

**Comment by bgirardot** [comment]
also with http://tasks.hotosm.org/project/591#task/67

**Comment by pgiraud** [comment]
This is due to an update in the code.
Same error happens with the following url.
http://tasks.hotosm.org/user/%E6%B8%A9%E5%AD%90%E6%BC%A2

The new code doesn't like non ascii characters for users' names.

**Comment by bgirardot** [comment]
Are you saying any task that has had someone work on it with a non ascii character in their name will cause the error?

**Comment by bgirardot** [comment]
chippy reports in irc it occurs on this task as well:
http://tasks.hotosm.org/project/945#task/316

**Comment by pgiraud** [comment]
Yep. I just started to debug that. I hope to get a workaround soon.

**Comment by bgirardot** [comment]
@pgiraud Nice, I tried to track it down and didn't have much luck :)

**Comment by pgiraud** [comment]
Part of the job is done here https://github.com/hotosm/osm-tasking-manager2/compare/hotosm:master...pgiraud:quote_encode?expand=1
We now need to add tests in order not to get a similar error later.
And it also needs to be done in `task.mako`.

**Comment by pierzen** [comment]
This time, selecting a tile not yet mapped, emergency Tanna island, Vanuatu, I recevie error message again
http://tasks.hotosm.org/project/945#task/331

**Comment by pierzen** [comment]
A contributor reports on the HOT list. This will give other tasks to test.

http://tasks.hotosm.org/project/945#task/316 and http://tasks.hotosm.org/project/945#task/331 are the only 2 remaining tasks that are not complete.
They are both showing 'an error occured'.

Had a similar problem with #591 Juba.

**Comment by pgiraud** [comment]
https://github.com/hotosm/osm-tasking-manager2/issues/563

**Comment by pgiraud** [comment]
Fixed with https://github.com/hotosm/osm-tasking-manager2/pull/566
And deployed!

**Comment by pierzen** [comment]
And many thanks !
