### ISSUE TITLE
Install in subfolder using nginx

### ISSUE THREAD

**Issue by LeOSW42** [hotosm/osm-tasking-manager2#569]
Hello world,

I'm trying since this morning to install OSMTM on my Debian Wheezy server.
Is there a documentation on how to serve the application to 127.0.0.1:6543, then how to redirect mydomain.com/osmtm to that using reverse proxy ?

Actually that works but pserve cannot serve HTML with absolute links to mydomain.com/osmtm

Thanks in advance

Léo

**Comment by pgiraud** [comment]
@dodobas any hint on how to configure nginx to serve the OSMTM wsgi app would be appreciated.

**Comment by LeOSW42** [comment]
Here is an example of nginx config to make a reverse proxy once the application is served on 127.0.0.1:6543

````
upstream tm_app_server {
    server 127.0.0.1:6543;
}

server {

    # Running port
    listen 80;
    server_name domain.com;

    # Proxy connections to the application servers
    # app_servers
    location / {

        proxy_pass         http://tm_app_server;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
}
````

You have to change `domain.com` with you current domain name
