### ISSUE TITLE
Dropdown Button not responding

### ISSUE THREAD

**Issue by olearytd** [hotosm/osm-tasking-manager2#585]
I'm not sure if I just did something different or wrong but I did a clone on the latest master this morning and after I get everything built and have my database, I am able to load up the local instance but nothing happens when I click either my username dropdown button or the language dropdown button.

I've run the console while trying to test what could be the issue and nothing shows up, and the url adds a hash at the end.

before click:
localhost:6543

after click:
localhost:6543/#

I have a clone from Feb. 24 that I haven't updated and when I run that local instance and try the same thing, the button works fine. 

I will attach an image if it helps, I can provide any other information required.

![feb24-master](https://cloud.githubusercontent.com/assets/6729929/7353893/0f483920-ece5-11e4-9876-2343cc0e9382.png)
![latest-master](https://cloud.githubusercontent.com/assets/6729929/7353773/32870ef8-ece4-11e4-8608-0d4fee85d447.png)

**Comment by olearytd** [comment]
The Feb24 clone is the top image, the lastest master is the bottom image.  

I can get the same results for the lastest clone if I do a checkout on commit:
61ce68b69dc11eb5cc586b834e4e0de60155a87a

**Comment by ethan-nelson** [comment]
Preliminary check ensures the menu is still programmed as a drop down: https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/templates/user_menu.mako#L5

Looking at the rest of the panel, I see the glyphicon is missing next to the page title. Both of these hint at an issue with bootstrap.

**Comment by olearytd** [comment]
It looks like my osmtm/static/boostrap directory is empty, do I need to run outside sources besides the install script?
./env/bin/python setup.py develop

**Comment by olearytd** [comment]
I copied the bootstrap files from my other repo into this new one and everything is working again.  Not sure if it is an actual fix but it will do, thanks for your help!

**Comment by ethan-nelson** [comment]
For the record, that often happens if `git clone http://` is executed without the `--recursive` flag.

**Comment by olearytd** [comment]
awesome, I'll try that next time.  Thanks for your help!

**Comment by ethan-nelson** [comment]
Glad to help...cheers :sunglasses:
