### ISSUE TITLE
Performance issues - Tasking Manager in the context of the Nepal Eartquake response

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager2#586]
The tasking manager is quite sollicited with this Nepal earthbrake. We had a problem that gladly Mikel if I remember was able to fix by parameters modification.

Should we need periodic backups and the capacity to move rapidly to an other server if any problem?

Other solutions that should be implemented?

**Comment by pgiraud** [comment]
The tasking manager is still missing stress testing. My bad.
However, I think the performances are really better than they were with the V1.

**Comment by pierzen** [comment]
stress live testing this wwek Pierre. going well. saww 150 contrib in one task. :)
  
Pierre 

      De : Pierre GIRAUD <notifications@github.com>
 À : hotosm/osm-tasking-manager2 <osm-tasking-manager2@noreply.github.com> 
Cc : Pierre Beland <infosbelas-am@yahoo.fr> 
 Envoyé le : Jeudi 30 avril 2015 9h50
 Objet : Re: [osm-tasking-manager2] Tasking Manager in the context of the Nepal Eartquake response (#586)
   
The tasking manager is still missing stress testing. My bad.
However, I think the performances are really better than they were with the V1.—

**Comment by pierzen** [comment]
stress live testing this wwek Pierre. going well. saww 150 contrib in one task. :)
thanks a lot. 
 
Pierre

**Comment by pierzen** [comment]
Often have problems to show the map with grids. Even if I try to reload the page.

**Comment by skalca** [comment]
On what kind of system is TM2 installed?

**Comment by pgiraud** [comment]
I propose we close this issue since the performance have been improved with latest release.
