### ISSUE TITLE
Do not allow validation of own task

### ISSUE THREAD

**Issue by planemad** [hotosm/osm-tasking-manager2#589]
Currently users can validate their own mapping task. This is not logical and should not be allowed.

This has been reported on the mailing list and is a major QA issue: https://lists.openstreetmap.org/pipermail/hot/2015-April/008420.html

**Comment by skalca** [comment]
Is it possible to get information from OSM user profile into TM2 about the number of edits made by the user? If so, maybe just users that have had made more than <some number> of edits, can validate their own mapping task (and/or of others).

**Comment by skalca** [comment]
Is this similar to #568?

**Comment by pierzen** [comment]
uneasy to establish. first thought 
since some 1 building == 1 changeset, at least 500 changesets, more then a month opened the account?

**Comment by aawiseman** [comment]
I think #568 can partially be helped by just getting more senior people to validate, sort of a culture shift. I have tried doing more of that and less actual mapping.

But I definitely agree that someone shouldn't be able to validate their own tasks, unless (maybe) they have lots of edits. And even then, not sure.

**Comment by skalca** [comment]
I agree. Both together would be great. 

Can TM2 get that kind of user info when a user performs login?

**Comment by skalca** [comment]
Well, according to the file **views/osmauth.py** TM2 only gets username out from OSM. Is this correct?

**Comment by ethan-nelson** [comment]
Username and id are taken from OSM API and stored in the User model.

**Comment by ethan-nelson** [comment]
This is actually easy to fix. I will have time to submit the pull request after dinner.

**Comment by ethan-nelson** [comment]
If we add `current user != user who marked done`, we should add an else clause that retains the button but adds the div id `disabled` with an updated tooltip letting the user know they cannot validate their own task. Otherwise we will get bug reports from people unaware saying the validate button is missing.

**Comment by ethan-nelson** [comment]
Writing down one other thought...we can't completely eliminate allowing a user to see the option to go into validation mode. If we do so, then a user could never self-invalidate a task. (Perhaps they caught themselves marking something done that shouldn't be).

**Comment by pierzen** [comment]
To provide some flexibility You should let the higher status editors have more control.

**Comment by planemad** [comment]
> Writing down one other thought...we can't completely eliminate allowing a
user to see the option to go into validation mode. If we do so, then a user
could never self-invalidate a task. (Perhaps they caught themselves marking
something done that shouldn't be).

Have clicked the mark task as done by mistake instead of unlock because it
was green and shiny, and am certain others do the same mistake as well.
Users should definitely have the option to self invalidate.


 <http://j.mp/ArunGanesh>

**Comment by skalca** [comment]
@planemad I might be missing something, but as I understand it, users can mark their work as done and validate work of the others. I think we are talking about validating your own work, and not marking it as done. 

Every user can still mark its work as done, but cannot validate it unless it has more than <that kind of number> modifications or has been a member of OSM for at least <so long>. 

Bottom line:
- users can mark their work as done.
- users **cannot** validate their **own** work unless specific criteria is met.
- users can **unmark** their work as undone if they mark it as done by mistake.

What does the main developer (@pgiraud) on the project think about this?

**Comment by skalca** [comment]
I just saw that github erased part of my comment. I wanted to say that only people with at least X number of modifications and people that have an open OSM account for at least Y number of days can validate work of the other (and self) people.

**Comment by CloCkWeRX** [comment]
There will be some annoyances as part of #602 being applied. IE; I sometimes invalidate, then realize it is actually only a small bit of mapping; perhaps I'm being too picky; do the mapping...  done -> validated -> comment added.

It's certainly much *less* common and probably less harmful than applying #602 , but I'm sure there are other legit use cases that might warrant this being a "really sternly discouraged action".

**Comment by pgiraud** [comment]
Initial issue "users can validate their own tasks" is fixed.
