### ISSUE TITLE
Require comment when validating or invalidating tasks

### ISSUE THREAD

**Issue by aawiseman** [hotosm/osm-tasking-manager2#592]
I've noticed a lot where somebody validates or invalidates a task but doesn't say why -- especially when invalidating, it would be helpful to know why that person thought it wasn't done. 

It might also be helpful to require it for marking a task as done, but to me validation is more important. 

Maybe it can include a message why you should leave a comment.

**Comment by mataharimhairi** [comment]
This is an excellent point Andrew, and perhaps should be a requirement that the user HAS to leave a comment before the option is even enabled to invalidate or validate a task.

**Comment by pgiraud** [comment]
@aawiseman Can you point me to a task that was invalidated and where the user didn't leave any comment?

As far as I know, the comment is required when you invalidate a task.
For example, you can try to invalidate this task and see if you're able to do it without leaving any comment. Don't be afraid, it's the testing instance.
http://tasks.dev.hotosm.org/project/736#task/1

**Comment by aawiseman** [comment]
Hi Pierre, I can't find it now because it has scrolled down the activity list, but it was in task 1004. I messaged one user about it, he is https://www.openstreetmap.org/user/Luccas%20Almeida if that helps.

**Comment by aawiseman** [comment]
@pgiraud then again I may be wrong! If that person didn't invalidate a task without a comment then please disregard! I may have been thinking about comments on marking as done and validating rather than invalidating.

**Comment by pgiraud** [comment]
Maybe the user left an empty comment (one blank space is enough).

Do you think that validating a task requires a comment?

**Comment by aawiseman** [comment]
Ah that may be it. I think commenting on marking a task as done is not a big deal, but maybe validating it would be helpful? Then again folks might just say "looks good" or "yes it is done"

**Comment by mataharimhairi** [comment]
No, probably just if they invalidate it. Is it possibly to make it so that a blank space isn't accepted as a comment and it has to be an A-Z character?

**Comment by pgiraud** [comment]
Feasible indeed (a line or two of javascript will do the job). Can we open a new issue to track that? (and close this one)
