### ISSUE TITLE
Clip project boundary and tasks by polygon

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-tasking-manager2#597]
This is a proposed feature to allow task creators the ability to clip the project extent (and its task tiles) by an existing polygon area. The clipping polygon could be uploaded as a zipped shapefile, GeoJSON or drawn manually on the map.

This feature would be useful in the case of individual imagery strips/scenes, to make sure the task coverage is recorded exactly for that imagery extent and not beyond. This will avoid any gaps or overlaps when creating adjacent tasks.

**Comment by bgirardot** [comment]
Cristiano, would supporting multiple imagery in a project, group of task squares by group of task squares adress this? Please see #883

**Comment by cgiovando** [comment]
We should close this one, as clipping can be done locally by reviewing and matching imagery, then the project polygon uploaded instead of drawing it manually. We should add this recommendation in the TM best practice guidebook, though ;)
