### ISSUE TITLE
Full language name is language picker drop-down menu

### ISSUE THREAD

**Issue by skalca** [hotosm/osm-tasking-manager2#608]
Currently the language picker drop-down menu just lists short "names" for the languages (eg. en, de, fr, etc...). I propose we make it look better and more user-friendly by using the language files. Menu should  show "English, Deutsch, Francais, Espanol, etc.." instead of "en, de, fr, etc...".

**Comment by ethan-nelson** [comment]
As I understand it, these abbreviations are the standardized abbreviations (ISO 639-1). I kind of like the minimal nature of the 2-5 characters too. 

That said, moving to the suggestion, languages are referred to by different names in other languages compared to the native ones--French versus Francais, Español versus Spanish versus Castilian, etc. So, if we do this, my question is whether we refer to the language by the self-language name (all languages would list Español instead of es), or by the translated name of the language in whichever translation is currently selected (Spanish if you have English selected, Español if you have Spanish selected, etc.)?

**Comment by skalca** [comment]
I would propose that we use self-language name for all translations (eg. __es__ is always listed as __Español__, etc...). It would also help that we only need to add _one_ additional line to ```development.ini``` file instead of introducing numerous new items into translation files.

**Comment by pgiraud** [comment]
+1 for writing the language name in the language itself

**Comment by althio** [comment]
> +1 for writing the language name in the language itself

another +1, this is the same in Wikipedia and our LearnOSM.

**Comment by skalca** [comment]
Ok, I have managed to change the menu, but I need opinion on two things:

1. Do I put flags beside each language name (https://www.flag-sprites.com or  https://github.com/lipis/flag-icon-css)
2. Do we need to change also language pick-up in _edit project_ for text input areas? Do we change buttons |en|es|fr|....|jp| to drop-down menus?

**Comment by pgiraud** [comment]
1. I would prefer we don't distract users with images. But if this is easy to set up, I would be happy to test it or see screenshots.
2. I don't think we need to change the look of the _edit project_ page. The _button group_ as several advantages compared to _dropdown menu_. It requires less clicks to change language and it quickly shows in which language the description has been translated.

**Comment by skalca** [comment]
Ok, so we go with number 2. Do we add hover titles with full language name to the buttons?

**Comment by althio** [comment]
> Do I put flags beside each language name (https://www.flag-sprites.com or
https://github.com/lipis/flag-icon-css

Cool but I would say no. Because some languages are used in several
countries and it is not possible to associate 1 flag, 1 language for
everything.

> Do we need to change also language pick-up in edit project for text input
areas? Do we change buttons |en|es|fr|....|jp| to drop-down menus?

It would look better IMO.

**Comment by skalca** [comment]
With flag-sprites you just append country ISO code to the html element and a correct flag shows up (hopefully). Well, I will make this change, and if you don't like it, it will be easy to remote it.

1 vs. 1 for edit project buttons... What now? :)

**Comment by althio** [comment]
- country ISO code (ISO 3166-1) and flag is hopefully a 1:1 relation.
- language ISO code (ISO 639-1) has *not* a 1:1 relation with country, or flag. Hopeless ;-)

**Comment by skalca** [comment]
We can still manually use proper flags and edit CSS file accordingly.

**Comment by ethan-nelson** [comment]
I think if we start adding language names on the edit window, we could get multiple rows of buttons which would clutter things. The two letter ISO codes probably suffice there. I do like using alt text to display the full name in that instance, though.

**Comment by skalca** [comment]
I have made a pull request, but only for first part (flag in menu). 

For the love of God, I could not figure it out how to get full language names into edit project template. I am entirely new to Pyramid framework and I just don't understand how to access variable defined in `base.mako` that is inherited into `project.edit.mako` and access it from there. The rest of the fix is just a matter of one line.

**Comment by ethan-nelson** [comment]
This is closed with #651
