### ISSUE TITLE
local.ini and production.ini location

### ISSUE THREAD

**Issue by geohacker** [hotosm/osm-tasking-manager2#609]
When I was setting up tasking manager, noticed that `production.ini` and `local.ini` are expected to be the home directory of the user. Is this the right practice? 

Why would not be picked up from the project root?  Should we [update docs](https://github.com/hotosm/osm-tasking-manager2/tree/2.10#local-settings)? 
Ref - https://github.com/hotosm/osm-tasking-manager2/blob/2.10/production.wsgi#L3 and https://github.com/hotosm/osm-tasking-manager2/blob/2.10/production.ini#L13

**Comment by skalca** [comment]
Are they supposed to be in the user home directory? I don't have them there (not at "root home" but instead a few dirs down the line) and the thing works. As I understand it, the README file states that both files can be anywhere else on the file system if you create a LOCAL_SETTINGS_PATH environment variable to make the project aware of this.

I think that ```here``` param in the ```production.ini``` file is based on this line ```here = os.path.abspath(os.path.dirname(__file__))```. @pgiraud correct me if I am wrong.

**Comment by ethan-nelson** [comment]
I believe they can be anywhere...the pserve command just needs to be told where it is.

For example, I have mine in the ~/osm-tasking-manager2 directory. Then, when I run the application I call `env/bin/pserve development.ini --reload`.

**Comment by pgiraud** [comment]
I will mark this as invalid since I don't think that the documentation tells you to put the `*.ini* files in home directory. Please tell us where you've seen this and I'll reopen the issue. There may be a misunderstanding in the doc.

**Comment by geohacker** [comment]
@pgiraud @ethan-nelson @skalca - thanks for the response. 
I'm not saying that the documentation instructs to put production.ini in the users home directory, but this is what I saw - 

```
[Thu May 14 09:40:03.867262 2015] [:error] [pid 19153] [remote 219.91.145.238:41434]     with open(filename) as f:
[Thu May 14 09:40:03.867276 2015] [:error] [pid 19153] [remote 219.91.145.238:41434] IOError: [Errno 2] No such file or directory: '/home/openstreetmap/production.ini'
```
Running mod-wsgi on apache.

@pgiraud - [docs](https://github.com/hotosm/osm-tasking-manager2#local-settings) say - 

> For this, you can create a local.ini file in the project root

which is what I did, but eventually had to move production.ini and local.ini to /home

Also, the [sample apache vhost configuration](https://github.com/hotosm/osm-tasking-manager2#installation-as-a-mod_wsgi-application) points to a wsgi file in `/home/ubuntu/osm-tasking-manager2/env/OSMTM.wsgi` but this is really `/osm-tasking-manager2/production.wsgi`

Again - just that I noticed this didn't match what the documentation said and might be worth fixing. Sorry if I'm missing something.

**Comment by pgiraud** [comment]
The vhost configuration is of course to be adapted to your context. This is an example. But you're right, since there's a `production.wsgi` configuration file in the code, the vhost configuration should be changed adequately. However, the path to this file is an example.
