### ISSUE TITLE
Add links to LearnOSM and MapGive to Right Hand Panel of TM Main Page

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-tasking-manager2#627]
The training working group and a few of the activation leads thought it would be a good idea to add links to learnOSM and MapGive Learn To Map to the main page of the tasking manager in the same area as the where to get help information.

**Comment by ethan-nelson** [comment]
Awesome. Did anything ever come to fruition regarding a meeting specifically for the TM? I haven't been on IRC much lately.

**Comment by rekth** [comment]
Hello! I am going to try to take care of this one.

**Comment by pgiraud** [comment]
The links are already in the about page.
I'm not against adding them in the from page as well though.
