### ISSUE TITLE
MapBox v4 url encoding

### ISSUE THREAD

**Issue by dalekunce** [hotosm/osm-tasking-manager2#634]
imagery layers hosted on MapBox and served with the v4 api do not load properly. The v4 api contains an access token parameter with the following parameters:

http://api.tiles.mapbox.com/v4/{mapid}/{z}/{x}/{y}.png?access_token={accesstoken}

The "?" in the url is not html encoded and is stripped when the user edits in iD editor. The imagery then fails to load. 

Solution would be to url encode all imagery urls.

**Comment by pgiraud** [comment]
Hi @dalekunce, do you have any example of a project where such a url is used?

**Comment by dalekunce** [comment]
I made a simple unpublished task to show this.

http://tasks.hotosm.org/project/1084

**Comment by ethan-nelson** [comment]
Can we confirm/deny if the issue occurs in potlach 2 and josm?

**Comment by ethan-nelson** [comment]
If someone else is interested in tackling this (I don't have time for a while), it would likely just require encoding `u` [here](https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/static/js/project.js#L488) and `imagery_url` [here](https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/static/js/project.js#L436).

**Comment by dalekunce** [comment]
Issue doesn't happen in josm as the imagery request is a stand alone
request using only the imagery uri.

I don't have a potlach compatible computer.

**Comment by mapmeld** [comment]
I just saw this same issue. The URL should be encoded before passing to iD. Potlatch2 and JOSM require the user to enter the imagery URL themselves, so they wouldn't be affected by this change.

**Comment by ethan-nelson** [comment]
Imagery URL is automatically sent to JOSM through remote control

**Comment by pgiraud** [comment]
Fixed with #656.
