### ISSUE TITLE
Fieldpapers link is dead

### ISSUE THREAD

**Issue by planemad** [hotosm/osm-tasking-manager2#638]
Following up on #285, the edit with field papers link is [dead](http://fieldpapers.org/make-step2-geography.php?lon=88.60611&lat=27.33639&zoom=18). It is not clear how this feature is supposed to work.

The link format is `http://fieldpapers.org/make-step2-geography.php?lon=88.60611&lat=27.33639&zoom=18`

**Comment by pgiraud** [comment]
Already fixed in https://github.com/hotosm/osm-tasking-manager2/pull/624.
Not deployed yet.
