### ISSUE TITLE
timeago locale for nl_NL should fallback to nl

### ISSUE THREAD

**Issue by milovanderlinden** [hotosm/osm-tasking-manager2#639]
When I set the language in the task manager to nl, I get a MakoRenderingException:

    IOError: [Errno 2] No such file or directory: u'/home/miblon/NetBeansProjects/osm-tasking-manager2    
    /osmtm/static/js/lib/jquery-timeago/locales/jquery.timeago.nl_NL.js'

Since timeago is an external dependency, I think it would be best if the application could fallback to

    jquery.timeago.nl.js

Which is present, instead of requesting

    jquery.timeago.nl_NL.js

**Comment by pgiraud** [comment]
Thanks @milovanderlinden for the report. I already addressed it though.
https://github.com/hotosm/osm-tasking-manager2/pull/633

Note: it has not been deployed yet.

**Comment by milovanderlinden** [comment]
Thanks, I can confirm that the fix works for 'nl_NL' fallback to 'nl'. Tested it in my fork.
