### ISSUE TITLE
bootstrap locale for nl_NL should fallback to nl

### ISSUE THREAD

**Issue by milovanderlinden** [hotosm/osm-tasking-manager2#642]
When I set the language in the task manager to nl, and after creating a new project (as administrator), I get a MakoRenderingException:
    IOError: [Errno 2] No such file or directory: u'/home/miblon/NetBeansProjects/osm-tasking-manager2/osmtm/static/js/lib/locales/bootstrap-datepicker.nl_NL.js'

Since bootstrap is an external dependency, I think it would be best if the application could fallback to

   bootstrap-datepicker.nl.js

Which is present, instead of requesting

    bootstrap-datepicker.nl_NL.js

I got the fix pending. It is based upon #633, but I will wait with a pull-request until my previous pull-request is accepted or rejected.

**Comment by pgiraud** [comment]
Using git branches should help you work on different issues at the same time.
