### ISSUE TITLE
Untranslated string: overpass-turbo

### ISSUE THREAD

**Issue by milovanderlinden** [hotosm/osm-tasking-manager2#647]
In the file task.mako, the string

    overpass-turbo

is not translated and should be replaced by

    ${_('overpass-turbo')

**Comment by pgiraud** [comment]
"Overpass-turbo" is the name of a tool. I don't think it has to be translated.

**Comment by milovanderlinden** [comment]
I think _all_ strings should be translatable, even if they are strings pointing to a tool where the translated text will possibly be the same as the english original.

**Comment by pierzen** [comment]
For Overpass, would be hard to translate I think. But the Task Manager is quite a descriptive name. My opinion is that is should be translated. Talking of it in french, I use the french expression Gestionnaire de tâches.
