### ISSUE TITLE
changeset comments in JOSM loaded incorrectly

### ISSUE THREAD

**Issue by danbjoseph** [hotosm/osm-tasking-manager2#650]
When JOSM automatically loads the comments from a task it displays incorrectly. See the screenshot below. The changeset comments are URL encoded.

![screen shot 2015-06-09 at 11 51 22 am](https://cloud.githubusercontent.com/assets/4806884/8082034/19359380-0f48-11e5-9eae-2850c6be0b2f.png)

This also affects how it shows up when changesets are searched out using a tool like [osm-meta-api](https://github.com/osmlab/osm-meta-api) 
```
    {
      "id": "30298990",
      "created_at": "2015-04-18T02:38:39Z",
      "closed_at": "2015-04-18T02:38:41Z",
      "open": "false",
      "num_changes": "22",
      "user": "dkunce",
      "uid": "1443840",
      "min_lat": "7.3816929",
      "max_lat": "7.3923856",
      "min_lon": "151.7069159",
      "max_lon": "151.7438204",
      "comments_count": "0",
      "source": "Bing",
      "created_by": "JOSM/1.5 (7906 en)",
      "comment": "%23hotosm-project-982%20%23RedCross%20%23Maysak"
    },
```

**Comment by ethan-nelson** [comment]
This should be fixed in #593, just not deployed yet.

**Comment by pgiraud** [comment]
This should have been fixed with the latest release which as been deployed a while ago now.
@danbjoseph can you confirm that it's fixed?

**Comment by danbjoseph** [comment]
Everything appears to be working properly. I'm using JOSM Version 8491, Last change at 2015-06-16 23:27:08 +0200 (Tue, 16 Jun 2015), Java Version 1.8.0_45

**Comment by ethan-nelson** [comment]
:+1:
