### ISSUE TITLE
500 error for /about page

### ISSUE THREAD

**Issue by Andygol** [hotosm/osm-tasking-manager2#652]
I tried to install HOT TM for tasking purpose - http://52.28.128.121/
And I faced with 500 error for last version of HOT TM while calling page `/about`

Look to the log I found : 

```
File "/home/ubuntu/osm-tasking-manager2/osmtm/templates/about.mako", line 63, in render_content
      <%
   File "build/bdist.linux-x86_64/egg/gitversion/__init__.py", line 42, in determine_git_version
     raise NoVersionError()
  NoVersionError:

```

here the problem with `gitversion` which cause 500 error 

Same issue are affected last installed instances:
- http://tasks.openstreetmap.org.ua/about
- same is here - http://tasks.openstreetmap.in/about

**Comment by tdyoma** [comment]
That problem is only when you switch project to 80 port from default 6543.

**Comment by Andygol** [comment]
Small additions:

This problem occurs when you run HOT TM as wsgi application with apache2

**Comment by ethan-nelson** [comment]
@Andygol when you deployed, did you remove the .git directory?

**Comment by Andygol** [comment]
@ethan-nelson No, I do not remove the `.git` dir

**Comment by ethan-nelson** [comment]
I think maybe that the server on which the tasking manager is installed cannot access github.com, which is required to pull in the version number. That quick fix prevents the page from crashing at least whenever it cannot access that.

**Comment by Andygol** [comment]
The problem is that when I run the server by command `./env/bin/pserve --reload development.ini` page `/about` is displayed as they should. But when I run service via apache with mod_wsgi I get `500` error for the `/about` page

Part of error log concerning this issue see in the 1st message

**Comment by pgiraud** [comment]
@Andygol it looks like it's possible to reach the about page in your instance. Did you change anything?

**Comment by Andygol** [comment]
@pgiraud 
yes, I applied code proposed @ethan-nelson as a temporary solution - https://github.com/hotosm/osm-tasking-manager2/pull/663

It is working but not showing info about version! - https://github.com/hotosm/osm-tasking-manager2/pull/663#issuecomment-113937540
![image](https://cloud.githubusercontent.com/assets/369696/8272800/32988d6c-185a-11e5-8b17-8a738ff3bf53.png)

**Comment by pgiraud** [comment]
We should probably use "git describe --always" instead of python-gitversion. It may be safier.

**Comment by pgiraud** [comment]
Pull request has been merged. #663
Leaving issue open. I'd rather give "git describe" a try.
