### ISSUE TITLE
"Draft" and "Archived" projects are accessible for everyone by their direct link

### ISSUE THREAD

**Issue by Andygol** [hotosm/osm-tasking-manager2#653]
People who have a direct link to a `draft` project can access to it

Is this a feature or a bug?

for example
* Draft 
 * http://tasks.hotosm.org/project/1061
 * http://tasks.hotosm.org/project/1061#task/57
* Archived 
 * http://tasks.hotosm.org/project/1089

**Comment by pgiraud** [comment]
Access to draft projects should now be fixed. See https://github.com/hotosm/osm-tasking-manager2/pull/629

**Comment by pgiraud** [comment]
It's not deployed yet though.

**Comment by pgiraud** [comment]
Archived projects are still reachable. Issue not completely fixed.

**Comment by ethan-nelson** [comment]
Both issues fixed now with #765 and #769
