### ISSUE TITLE
Language of the interface is not switched 

### ISSUE THREAD

**Issue by Andygol** [hotosm/osm-tasking-manager2#654]
![hot_tm_ln_sw](https://cloud.githubusercontent.com/assets/369696/8110451/01b227be-1065-11e5-9efa-f809be047b8b.gif)

This issue affects latest installed instances:
http://tasks.openstreetmap.in/ and http://tasks.openstreetmap.org.ua

**Comment by pgiraud** [comment]
You probably need to compile the catalog.
```
.env/bin/python setup.py compile_catalog
```

**Comment by Andygol** [comment]
yeah! :+1: 
@pgiraud thanks for help :rocket: 

one more request:
Could you merge Ukrainian translation from transifex?

**Comment by geohacker** [comment]
@Andygol Will take care of this. Thanks for the heads-up @pgiraud. Does it make sense to add this in the docs too? I can do that.

**Comment by geohacker** [comment]
Just [found](https://github.com/hotosm/osm-tasking-manager2#initializing-translation-files).
