### ISSUE TITLE
Unable to pick date from calendar

### ISSUE THREAD

**Issue by Andygol** [hotosm/osm-tasking-manager2#664]
When I try to select the end date of the project through the calendar - it does not open (see pic below). 
When I try to enter the date manually - the server responds with an error 500. I found the following in the server log when I tried put the date "22.06.2015"

```
[Sun Jun 21 15:55:37.043370 2015] [:error]      return view(context, request)
[Sun Jun 21 15:55:37.043379 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 352, in rendered_view
[Sun Jun 21 15:55:37.043391 2015] [:error]      result = view(context, request)
[Sun Jun 21 15:55:37.043398 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 506, in _requestonly_view
[Sun Jun 21 15:55:37.043410 2015] [:error]      response = view(request)
[Sun Jun 21 15:55:37.043417 2015] [:error]    File "/home/ubuntu/osm-tasking-manager2/osmtm/views/project.py", line 266, in project_edit
[Sun Jun 21 15:55:37.043429 2015] [:error]      due_date = datetime.datetime.strptime(due_date, "%m/%d/%Y")
[Sun Jun 21 15:55:37.043440 2015] [:error]    File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
[Sun Jun 21 15:55:37.043453 2015] [:error]      (data_string, format))
[Sun Jun 21 15:55:37.043478 2015] [:error]  ValueError: time data '22.06.2015' does not match format '%m/%d/%Y'
```

![hot_tm_pick_date](https://cloud.githubusercontent.com/assets/369696/8272420/50b0b46a-184a-11e5-94a1-1cc367f75cc0.gif)

**Comment by ethan-nelson** [comment]
The date must be entered in the format MM/DD/YYYY, though we should probably explicitly state this on the page. That said, my local install automatically changes the date if it's not invalid to one that is (in this case 22.06.2015 changed to 10.06.2015).

**Comment by Andygol** [comment]
What about pick date from calendar?
I can't able pick date from it. When I clicked on the calendar-button nothing happened!

**Comment by ethan-nelson** [comment]
Check the javascript console whenever you're on the page to see if there are any loading errors. The date time picker library may not be loading.

**Comment by Andygol** [comment]
@ethan-nelson 
Thanks for suggestion. It was my fault. I incorrectly made a comment in the code so the library to display the calendar was not loaded.

But issue about automatically date conversion is still present - https://github.com/osm-ua/osm-tasking-manager2/issues/2#issuecomment-113935677
