### ISSUE TITLE
AttributeError: available_languages_full

### ISSUE THREAD

**Issue by hyances** [hotosm/osm-tasking-manager2#666]
Recenlty I made a ```$git pull origin master``` to http://tareas.openstreetmap.co then follow deployment instructions on README, now this error appear in the browser

```Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)```

Traceback here:

http://paste.ubuntu.com/11823537/

Thanks for your help!

**Comment by pgiraud** [comment]
Can you ensure that the "available_languages_full" is set in your ".ini" file? (either `development.ini` or `production.ini`)

**Comment by hyances** [comment]
Thanks, I just merge to 2.11 and left original development.ini, changing only [server:main] parameters.  Running!  (or is recommended 2.12-dev?)

**Comment by pgiraud** [comment]
Relying on a stable version might be a good idea. And there's nothing new in 2.12-dev actually.
