### ISSUE TITLE
DistributionNotFound: The '********' distribution was not found and is required by osmtm 

### ISSUE THREAD

**Issue by baditaflorin** [hotosm/osm-tasking-manager2#669]
not sure what i did different now then the last time i have installed the machine, but now i get this error every single time, and after i install one of them, lets say waitress, then if i try 
./env/bin/initialize_osmtm_db

i will get a error that i had not installed zope.sqlalchemy 

after i install this, i will get an error if i try to run 
./env/bin/initialize_osmtm_db
Telling me that i had not installed pyramid-debugtoolbar

A complete list until now of what i had to install looks like this : 
Could i find a list with all the requirements so i can issue a command and install all in once, not discover one by one ?

./env/bin/pip install psycopg2

./env/bin/pip install waitress

./env/bin/pip install zope.sqlalchemy

./env/bin/pip install pyramid-debugtoolbar

./env/bin/pip install pyramid-tm

./env/bin/pip install SQLAlchemy==0.9.9

./env/bin/pip install pyramid==1.6a1

./env/bin/pip install futures

./env/bin/pip install tzlocal

./env/bin/pip install six>=1.4.0

./env/bin/pip install beautifulsoup4

./env/bin/pip install httplib2

./env/bin/pip install html5lib>=0.999

**Comment by baditaflorin** [comment]
Funny, i have posted the bug request and after that i tried it again, waiting to complete the list with more distributions that the program needed. And it worked, so this is the list with all the requirements.

**Comment by pgiraud** [comment]
Are you sure you correctly install the application? (ie. run the setup.py
develop command)

On Fri, Jul 10, 2015 at 5:52 PM, baditaflorin <notifications@github.com>
wrote:

> Funny, i have posted the bug request and after that i tried it again,
> waiting to complete the list with more distributions that the program
> needed. And it worked, so this is the list with all the requirements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hotosm/osm-tasking-manager2/issues/669#issuecomment-120442612>
> .
>



-- 
-------------------------------------------------------------
  | Pierre GIRAUD
-------------------------------------------------------------

**Comment by pgiraud** [comment]
@baditaflorin what's the status of this issue?
