### ISSUE TITLE
Customize basemap for a task

### ISSUE THREAD

**Issue by planemad** [hotosm/osm-tasking-manager2#682]
An option to customize the basemap for a task will help us use different styles to focus mapping activity better. 

For eg. I would like to use a visualization of routing errors as the basemap that will help mappers prioritize which blocks need to be worked on first and which to ignore. The humanitarian OSM layer is not very useful for this.
![screenshot 2015-09-30 12 42 40](https://cloud.githubusercontent.com/assets/126868/10186717/e2c6b802-6770-11e5-91c3-536b123a8c35.png)
The tileurl is `tms:http://{switch:a,b,c}.tiles.mapbox.com/v4/planemad.c2f80b8f/{zoom}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJncjlmd0t3In0.DmZsIeOW-3x-C5eX-wAqTw`

Is there a way this can be configured easily on a task to task basis?

**Comment by ethan-nelson** [comment]
This unfortunately requires tweaking javascript code. But we may be able to potentially load in a custom basemap by adding `<script></script>` tags at the top of one of the project templates so that the custom variable is present before the map initializes.

**Comment by althio** [comment]
see also #497

**Comment by bgirardot** [comment]
Between #497 and #838 I am going to close this one as it is a duplicate.
