### ISSUE TITLE
Make default comment tag a config variable or property of a project

### ISSUE THREAD

**Issue by batpad** [hotosm/osm-tasking-manager2#688]
Right now the default changeset comment seems to be hard-coded here: https://github.com/hotosm/osm-tasking-manager2/blob/5d8e3f91145c5f6993c588be86a8130cfd738d12/osmtm/models.py#L620

Would be nice if this can either be a configuration parameter per instance, or per project (not sure which is more ideal).

If this seems sensible, am happy to take a stab at it and make a PR.

**Comment by pgiraud** [comment]
The project managers can actually change this "changeset comment" when editing a project.
If you still think that you need a "per-instance" value, please provide a PR.

**Comment by planemad** [comment]
Yes, a per instance value would be very handy to differentiate changesets coming from hotosm, teachosm and other instances like the [India tasking manager](http://tasks.openstreetmap.in). Since the comment is generated automatically for each task, it saves the extra effort of removing #hotosm each time manually.

**Comment by batpad** [comment]
Ah - my bad here, mis-framed the issue, apologies.

I agree with @pgiraud that being able to edit it on a per-project basis should solve this use-case. 

However, @planemad, I do see that this default has caused some projects to get accidentally labelled `#hotosm-` and that causes a few problems. @pgiraud if you're open to a pull request, I'll spend some time understanding local settings in pyramid exactly and how to write tests for this, etc. and try and cut a PR for this next week. Thanks!

**Comment by pgiraud** [comment]
@batpad The `local.ini` file is probably a good candidate for adding per-instance configuration.

**Comment by batpad** [comment]
@pgiraud yep, thanks, that is what I thought. I am just reading up on Pyramid / figuring out the cleanest way to access the site config from inside models / views.

In Django one would do `from django.conf import settings`. Am trying to see what the equivalent way in Pyramid is, ideally without re-parsing the local.ini file.

**Comment by pgiraud** [comment]
@batpad Not necessarily the best pyramid way to do it but check out `load_local_settings`in osmtm.utils.
https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/utils.py#L58

It's already used in different locations.

**Comment by batpad** [comment]
hey @pgiraud thanks!

Defining a setting in local.ini seemed to be picked up fine by the Configurator.

I used `from pyramid.threadlocal import get_current_registry` to get the settings object inside the models file, as per http://stackoverflow.com/questions/10893628/how-can-i-get-the-ini-data-in-pyramid

Then needed to make some changes to get the current tests to pass, as per http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/testing.html#test-set-up-and-tear-down

You can see my commit here: https://github.com/osm-in/osm-tasking-manager2/commit/0b05415725d24e263d8740ea4baba1f5c236c613

If this seems reasonable, I will go ahead and do some clean-up and write tests to test this feature and make a PR. Please also give me feedback on the name of the config parameter - right now have called it `default_comment_prefix`.

If you think this is not the right approach, please let me know! Thanks @pgiraud !

**Comment by pgiraud** [comment]
Hi @batpad, I hope I'll find time soon to have a look at your code.

**Comment by batpad** [comment]
No worries. Thanks @pgiraud ! Let me know if there's anything I can do to make it easier for you to parse through.

**Comment by pgiraud** [comment]
Hi @batpad,
Can you please create a pull request with your commit?

**Comment by batpad** [comment]
@pgiraud look forward to hearing your thoughts. Thank you.

**Comment by ethan-nelson** [comment]
Fixed via #695
