### ISSUE TITLE
"New to Mapping" TM front page text section needs to be made translateable.

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-tasking-manager2#692]
We added a "new to mapping" section quickly to the live TM front page for Hurricane Patricia and Afghanistan EQ activation and that needs to be done properly in the code now so it can be translated.

**Comment by ethan-nelson** [comment]
Are we also still interested in sending a mail via the TM to new users when they access it for the first time?

**Comment by ethan-nelson** [comment]
@pgiraud I believe this can be closed based on the pull request
