### ISSUE TITLE
Use protocol relative URLs

### ISSUE THREAD

**Issue by dodobas** [hotosm/osm-tasking-manager2#693]
Some resources, like tiles on the openstreetmap.fr servers are *hardcoded* to http, we should use protocol relative URLs [http://billpatrianakos.me/blog/2013/04/18/protocol-relative-urls/]

**Comment by dodobas** [comment]
user profile page fetches some data from http://openstreetmap.org

**Comment by pgiraud** [comment]
> user profile page fetches some data from http://openstreetmap.org

I don't really know what you mean.
I changed the protocol to https but the written test fail.
