### ISSUE TITLE
i18n for donations banner

### ISSUE THREAD

**Issue by vgeorge** [hotosm/osm-tasking-manager2#711]
I saw that it is internationalized here, but I didn't find it at Transifex. I assume you couldn't push changes yet.

**Comment by pgiraud** [comment]
@vgeorge What do you mean by "here"?
There's a pull request pending to add the donation banner to the master branch. With translations enabled. When merged, the Transifex will be updated.

**Comment by vgeorge** [comment]
At this repository, thanks for the heads up.

**Comment by pgiraud** [comment]
The donate banner has been removed. Closing.
