### ISSUE TITLE
JOSM Remote Control not working when clicking on the 'Edit with JOSM' button

### ISSUE THREAD

**Issue by d3netxer** [hotosm/osm-tasking-manager2#712]
Looking at the console, I am getting this error message outputted:

Mixed Content: The page at 'https://tasks.hotosm.org/project/1359#task/104' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://127.0.0.1:8111/load_and_zoom?left=-80.60669&bottom=-5.25507&right=-8…%2Fhot%2F1.0.0%2Fpiura-24nov2015-flipped%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png'. This request has been blocked; the content must be served over HTTPS.

So maybe then JOSM doesn't like that mixed content is being served. 

What if we change the line on 420 of the project.js file:

```
    base: 'http://127.0.0.1:8111/load_and_zoom?',
```

to be https ?

Maybe the drawback would be that the user would have to check the box 'enable https support' in their JOSM preferences? But I'm not sure how I can get the remote control to work in the current state.

**Comment by bgirardot** [comment]
We backed out some https support due to mixed content issues. @d3netxer Did that also resolve this issue?

**Comment by d3netxer** [comment]
I tested the same square with JOSM and did not encounter this issue. Thanks
