### ISSUE TITLE
Contact all contributors to a project button

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-tasking-manager2#719]
I would like a way to send a message (TM internal, or opt-in'ed email (I know TM doesn't sent emails)) to all the users who have contributed to a project. For now I think the list of people who are in the "stats" tab would be enough, knowing that eventually validators will be listed there :)

Some use cases are to thank people, let them know of changes to instructions, or in my current case, let them know we are creating new TM projects related to the project they have already contributed to and the current project will be archived.

**Comment by dalekunce** [comment]
+1 this is a great idea and one that could hopefully drive repeat volunteers.

**Comment by mnoblecourt** [comment]
+1 this would be a great feature to thank users and also send feedback on how their contribution was used (e.g. send the map produced by an NGO with the data, a photo of people using the data in the field...)

**Comment by ethan-nelson** [comment]
I was planning to work on this but had one question about database space. I'm not a big backend developer, so I'm wondering if this mass of mails is something the database is designed for. If we have 100 editors and validators on a task, and we do that a few times, the numbers will be quite high. But if either 1) this behavior is completely ordinary and fine or 2) there is a more optimal way to approach that, I'm happy to put time in on this task :)

**Comment by ethan-nelson** [comment]
I mention that also because this opens up the messaging in the tasking manager a lot more than before. Previously--to my knowledge--mails would only be sent for validation/invalidation or comments. If we do this, would we not also want to open up the opportunity to message the senders back? Do we want to restrict it to between those two people (the mass sender and the respondent) or also open up TM messaging to/from anyone?

**Comment by bgirardot** [comment]
Hi @ethan-nelson you are right this is a pretty major addition to the TM. If you can work on it, I can write up my thoughts about the best way to handle it. It will take adding some core functionality to the TM and taking a few different uses of that new functionality into account. Please let me know and I'll get a write up on the uses cases as I see them for actual emails done.

**Comment by bgirardot** [comment]
Hi @ethan-nelson did you have any thoughts about working on this feature? The missing maps folks are pretty eager to get it added and I think I can spec it out pretty well.

**Comment by ethan-nelson** [comment]
My original comment was definitely a little aggressive in the capabilities I was thinking to be added. For now, I think adding project manager->user would be a good starting point that hopefully shouldn't cause too much volume. I apparently glossed over your original reply so I will come back to adding this soon (likely from the project edit page).

**Comment by ethan-nelson** [comment]
Blake, I now have a hacked together version working. I'll try to clean it up and get something pull requested over the weekend.

**Comment by ethan-nelson** [comment]
@bgirardot cobbled together things here https://github.com/ethan-nelson/osm-tasking-manager2/commit/7fd378aedc9dab5c87a880fec9f48a459c5da8ff by mostly recycling other code in the project. I still need to write a test for it before I make the pull request, but if you want to try it out as well locally you're welcome to.
