### ISSUE TITLE
Typo in "about" text - translations duplicated

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager2#720]
The following textes should be the same:
https://github.com/hotosm/osm-tasking-manager2/blob/5d8e3f91145c5f6993c588be86a8130cfd738d12/osmtm/templates/about.mako#L12
https://github.com/hotosm/osm-tasking-manager2/blob/9f1dfbdc41db3b2028f82aacb4c494d1a9edeb56/osmtm/templates/home.mako#L95

They're not. Actually there's a small difference ("homogeinity" vs. "homogeneity") which makes the tool think that there are 2 different translations.
See https://www.transifex.com/hotosm/osm-tasking-manager2/translate/#cs/master/50802315

**Comment by ethan-nelson** [comment]
Fixed in #722
