### ISSUE TITLE
Allow images and videos in Tasking Manager description and/or instructions

### ISSUE THREAD

**Issue by aawiseman** [hotosm/osm-tasking-manager2#721]
I think this would be helpful, especially where there are tutorial videos or images that would help show what to look for -- like tracing guides, task-specific features, and such. I think (?) it would require some specialized Markdown to do it, but in doing some research I saw others make tags: https://blog.snipt.net/embed-youtube-videos-into-your-markdown-flavored-snipts/

**Comment by bgirardot** [comment]
As I recall images should be possible in the description and instructions but due to a bug they do not display in the instructions.

I agree, embedded videos would be helpful as well.

**Comment by aawiseman** [comment]
Yeah, I've tested putting in images and it doesn't work. Best I can do is link to it and I think having the image or video would make it much more clear. Imagine if you could put little gifs that show what to do or videos that explain the task!

**Comment by Courtney-Clark** [comment]
I agree as well! We have amazing photos and videos about projects from the field, and it would be so motivating to mappers to see that content. It can also help provide much more context about a project than a paragraph description. I would use this all the time.

**Comment by dalekunce** [comment]
:+1:

**Comment by wuhland** [comment]
I want!!!

**Comment by jasmin530** [comment]
I agree!

**Comment by Geocruizer** [comment]
Yes that would be very helpful Andrew, great suggestion.
