### ISSUE TITLE
Move archived projects to the end of what a task creator sees

### ISSUE THREAD

**Issue by Courtney-Clark** [hotosm/osm-tasking-manager2#723]
I create and archive a lot of tasks, and I often am logged in to the TM when I am demonstrating how to use it during trainings, webinars, etc. It's confusing/not very professional for my training audiences when I am showing them my screen with a jumble of active and archived tasks and they only see the active tasks on their own screens. It also makes it less efficient for me to quickly view all of my active tasks and have a sense of what needs work, etc. At least have a filter option so I can choose to only see active tasks, only draft tasks, only archived, etc.

**Comment by dalekunce** [comment]
:+1:

**Comment by jasmin530** [comment]
I agree @Courtney-Clark and @dalekunce.

**Comment by ethan-nelson** [comment]
I can work on adding a check box like there is for `Your Projects` that would enable showing archived projects (meaning by default they will be hidden). As for drafts, I think it would be more preferable to have those visible by default?

**Comment by ethan-nelson** [comment]
Fixed in #772. Archived projects will be hidden by default, but there is a check box to show them. 

![](https://cloud.githubusercontent.com/assets/8998918/14758475/fdf656ca-08c7-11e6-81fa-303e47c69b26.PNG)
