### ISSUE TITLE
Export original task boundary as GeoJSON

### ISSUE THREAD

**Issue by pratikyadav** [hotosm/osm-tasking-manager2#729]
Currently the `export` button let you download the boundary for tasks created by Tasking Manager. It doesn't let you download the original task boundary geoJSON used for creating the task.

This original task boundary can be downloaded using URL `http://tasks.hotosm.org/project/<task>.json`(may be a bug)

Would be nice to have both original and task/tiles in one geojson file via `export` button.

**Comment by pgiraud** [comment]
You're right, the project geometry is available through `http://tasks.hotosm.org/project/<project_id>.json`.
The tasks (squares) are available at `http://tasks.hotosm.org/project/<project_id>/tasks.json`.

I'd prefer to keep them separated in order to prevent different types of data to be mixed.

**Comment by maning** [comment]
@pgiraud Cool to know this exist.  Where's the place to document this?

**Comment by pgiraud** [comment]
This Wiki page could be the right place: https://github.com/hotosm/osm-tasking-manager2/wiki/API
However, it's not up-to-date.

**Comment by pgiraud** [comment]
@pratikyadav Can I close this issue?

**Comment by pratikyadav** [comment]
:+1:
