### ISSUE TITLE
How to download OSM file from a URL in the import_url properties imported geojson

### ISSUE THREAD

**Issue by maning** [hotosm/osm-tasking-manager2#734]
In the previous TM, you can create a geojson with an `import_url` property where it contains an OSM file for a specific task (see: http://wiki.openstreetmap.org/wiki/Tasking_manager_admin).  In the current instance, you do this by specifying a URL like `http://localhost:8111/import?new_layer=true&url=http://www.domain.com/data/{x}/{y}/{z}/routes_2009.osm` in the **Extra Instructions**.  

How can I do this by reading the URL in imported geojson properties as the former behavior?

**Comment by pgiraud** [comment]
You should be able to convert your .osm file to GeoJSON using http://geojson.io.

See the help comment below the import button in the new project page.
![screenshot from 2016-01-19 11 25 57](https://cloud.githubusercontent.com/assets/319774/12416055/75830f62-be9f-11e5-9f69-ac2068fcb89d.png)

**Comment by maning** [comment]
@pgiraud Sorry, I may not be clear on my question.  I can already import the polys a geojson.  What I want is to load a custom OSM file for each task/block.  In the previous, TM you can do this by creating an import_url as the source of the osm file.

**Comment by pgiraud** [comment]
Related to https://github.com/hotosm/osm-tasking-manager2/issues/684 and https://github.com/hotosm/osm-tasking-manager2/issues/675

**Comment by maning** [comment]
@pgiraud, me and @batpad sketched out a test implementation for this.  
The URL to an OSM file for each task was added in the geojson `import_url` property.  The TM then parses this property to display a link which will download the data via JOSM RC.  The code is very rough and we want to refine the UI behavior. See GIF below:

![tm_bam-compressor](https://cloud.githubusercontent.com/assets/353700/12480476/9ec26966-c068-11e5-9bb8-a3c5eca15f66.gif)

@batpad will do more tweaks and tests before submitting a PR.

**Comment by dalekunce** [comment]
@maning this looks very promising. Do you think its possible to have it as an option in during the TM creation. This will allow the current UI/UX to remain the same and make the admin of the feature a little cleaner.

I love seeing this move forward.

**Comment by maning** [comment]
This is now in master. Closing.
