### ISSUE TITLE
Add configuration options for the donate ribbon 

### ISSUE THREAD

**Issue by dodobas** [hotosm/osm-tasking-manager2#746]
Please add a configuration flag to toggle visibility of the donate ribbon as we would like to be able to show it conditionally.

Also add the configuration option for the link of the donate ribbon

**Comment by pgiraud** [comment]
The donate ribbon and the corresponding link are defined in the `custom.mako` file. This file is intended to be modified by user in their own instance.
https://github.com/hotosm/osm-tasking-manager2#customization

Do you think it's worth adding configuration specifically for the ribbon?

**Comment by dodobas** [comment]
ok, that's fine
