### ISSUE TITLE
API doesn't return archived projects

### ISSUE THREAD

**Issue by tyrasd** [hotosm/osm-tasking-manager2#787]
(from https://github.com/hotosm/osm-analytics/issues/28#issuecomment-214808738): 
TM's [API](https://github.com/hotosm/osm-tasking-manager2/wiki/API#list-of-projects) (`GET /projects.json`) doesn't return *archived* projects such as [#1838](http://tasks.hotosm.org/project/1838). Is that intentional?

edit: on the other hand, the "private" project [#310](http://tasks.hotosm.org/project/310) is included in the output even though the documentation states that “private projects will not appear in this list”.

**Comment by ethan-nelson** [comment]
Interesting. As I understand it, projects.json essentially returns a project list identical to the projects that appear on the home page (though more shown in the json file). So my question is then

When getting the projects.json file, are you logged in as:
a) an admin
b) a project manager for project 310
c) a project manager but not for project 310
d) a user allowed for project 310
e) a user not allowed for project 310
f) anonymous/not logged in

**Comment by ethan-nelson** [comment]
Also as a side note, project 310--in spite of its name--is not a private project.

**Comment by ethan-nelson** [comment]
But, if someone is logged in as a regular user, they will not have access to archived projects (we have received feedback from project managers to prevent access because otherwise users may continue to go directly to the project and work on it in spite of its archived status).

It was reported in #653 that users could still reach archived projects by direct link and that was fixed in #769 very recently--that patch will eventually reach the live server in the next deployment. Thus, for archived projects to appear in `projects.json`, a user currently needs project manager or admin status (roles that are able to still view archived projects).

**Comment by tyrasd** [comment]
I'm not logged in at all when requesting the project list.

My use case is displaying a hot project overlay on http://osm-analytics.org/, for which especially the already completed *archived* projects are useful and interesting. Maybe adding a parameter to the API call that allows to fetch active and archived projects would make sense?

**Comment by ethan-nelson** [comment]
Well, with the next patch, archived projects will be available with the ?show_archived=on value on the url. But again, the permissions to view an archived project will still rely on the user being an admin or project manager. @pgiraud i don't know if we want to rethink that functionality. Potentially we could still give everyone access to archived projects but instead lock down the ability to add comments or take tiles.

**Comment by tyrasd** [comment]
OK, perfect. (Sorry, I didn't see that #772 was already just about this.)

> Potentially we could still give everyone access to archived projects but instead lock down the ability to add comments or take tiles.

:+1:

**Comment by bgirardot** [comment]
I am not rushing anyone at all, but I created #810 that is about this same issue because we just ran into it.

Can we leave this one closed and just close #810 when it is actually deployed?
