### ISSUE TITLE
iD editor and Firefox 46

### ISSUE THREAD

**Issue by scruss** [hotosm/osm-tasking-manager2#795]
In the OSM Canada tasking manager, attempting to use iD as the editor produces an URL that leaves a blank screen.Possibly a Mixed Content blocking issue: https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox?redirectlocale=en-US&as=u&redirectslug=how-does-content-isnt-secure-affect-my-safety&utm_source=inproduct

Browser: Firefox 46.0
Plugins: Ublock Origin, Privacy Badger, HTTPS Everywhere, Flash removed
System: Linux (Ubuntu 16.04, x86_64)

Example link (poss expired): https://www.openstreetmap.org/edit?editor=id&#map=17/56.6713202392/-111.318969707&comment=%23osmcanada-FortMcMurray-project-22&gpx=http://tasks.osmcanada.ca/project/22/task/599.gpx

Result: OSM edit screen with no editor, just blank white space.

**Comment by ethan-nelson** [comment]
Thanks for the report!

I was unable to replicate this in Firefox 43.0.4, but once I upgraded to Firefox 46.0 I came upon the same editor. If you click the padlock with the exclamation mark to the left of the url field in the top of the FireFox browser and then click disable protection, it will work.

**Comment by ethan-nelson** [comment]
As you alluded to, it appears the problem stems from loading the *.gpx file using non-https.

**Comment by ethan-nelson** [comment]
Looks to be similar to #777

**Comment by scruss** [comment]
Yes, seems identical to #777 - sorry I didn't catch that.

Not interested in turning https off, personally.
