### ISSUE TITLE
Add Tamil (ta) and Sinhalese (si) language

### ISSUE THREAD

**Issue by maning** [hotosm/osm-tasking-manager2#799]
Related to the current flood mapping in Sri Lanka, we need to add new language codes (ta, si) to translate the instructions

**Comment by maning** [comment]
@pgiraud @ethan-nelson We can do Tamil translation if this is available.

**Comment by batpad** [comment]
Let me know if there's anything I can do to help here. Not sure how the translation flow works exactly, but if there's a development lift involved here, if you point me to what to do @pgiraud @ethan-nelson am happy to take it on, if it helps.

**Comment by maning** [comment]
I've requested a Tamil langugae in transifex: https://www.transifex.com/hotosm/osm-tasking-manager2/
Per irc with @dodobas, we need to get this translation first before adding the language option within the deployed TM instance.

**Comment by maning** [comment]
Tamil is 36% done.  I also requested for Sinhala.  It would be great to have the option available in the TM in light Sri Lanka activation. We also did translations for the project details/instructions.

**Comment by ethan-nelson** [comment]
Wow, nice work so far!

**Comment by pgiraud** [comment]
Done in 2.12 branch (2.12.x releases).
Will hopefully be deployed soon.
Closing.
