### ISSUE TITLE
Missing translations due to old jQuery-timeago

### ISSUE THREAD

**Issue by ProtD** [hotosm/osm-tasking-manager2#818]
In some languages, at least Czech, the Tasking manager contains English wording such as "_about 5 hours ago_", even though the rest of the page is translated. This is probably because a [jQuery-timeago](https://github.com/rmm5t/jquery-timeago/tree/61980c6e2237f9b444b682c63dc19bcc9e738680) plugin from _3 years ago_ :-) is used, which contained a wrong language code (cz instead of cs). Current version is OK, so an update would fix it.

**Comment by pgiraud** [comment]
Oh. I didn't figure this out. Thanks for the detailed report.
I'll do my best to update this as soon as possible.

**Comment by pgiraud** [comment]
Will be deployed soon.

**Comment by ProtD** [comment]
Thanks! Just checked the website and it's OK now.
