### ISSUE TITLE
% complete in API wrong

### ISSUE THREAD

**Issue by dalekunce** [hotosm/osm-tasking-manager2#833]
we noticed that the TM API is giving the wrong % complete.

https://github.com/MissingMaps/partners/issues/26

**Comment by pgiraud** [comment]
"done" and "validated" are states. What the API returns is the actual count of tiles that have the "done" & "validated" status.

In TM UI, we cheat a bit by considering that "validated" tiles are also "done". So we concatenate the values for "done" to get the percentage of completeness.

Does it make sense?
