### ISSUE TITLE
Encoding or Support Format of url TMS

### ISSUE THREAD

**Issue by kleper** [hotosm/osm-tasking-manager2#834]
I am a user of TM of OpenStreetMap Colombia. I trying use a image from a GeoServer instance, this server provide a TMS url like this:

http://geonode.server/geoserver/gwc/service/gmaps?layers=geonode:layer&zoom={z}&x={x}&y={y}&format=image/png8

When i try load a task with this tms, on JOSM, the tasking manager are send me a url like this:

http://geonode.server/geoserver/gwc/service/gmaps?layers=geonode:layer&amp;zoom=19&amp;x=148716&amp;y=258397&amp;format=image/png8

The url are corrupted by the TaskManger, with this aditional text: &amp. Something is changing the encoding of the url.

I know that the Task Manajer support only this kind of url: tms[22]:http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{zoom}/{x}/{y}.png but on some cases the users can't modify the url.

Thanks.

**Comment by alejandroscf** [comment]
That's not working yet. Looks like the '&' char is converted to it HTML representation, breaking the url.

**Comment by alejandroscf** [comment]
The url for imagery is correctly stored in the database, the substitution of '&' to '&amp;' is done in the line 87 of file [/osmtm/templates/task.mako](https://github.com/hotosm/osm-tasking-manager2/blob/61e712eb211b9d770c77d1db898b6fa59516adbd/osmtm/templates/task.mako#L87), if you change it for `var imagery_url = "${project.imagery|n}";` it works ok.
I don't think this could cause a security breach for injection as this parameter can only be set by users with privileges to create new tasks.

Please find attached the patch with the change. [patch.txt](https://github.com/hotosm/osm-tasking-manager2/files/671826/patch.txt) I can prepare a pull request if necessary.

Best regards,
Alejandro

**Comment by pgiraud** [comment]
@alejandroscf please do! Thanks.
