### ISSUE TITLE
Make it easier to set up custom non-HOT branded version of tm

### ISSUE THREAD

**Issue by tyrasd** [hotosm/osm-tasking-manager2#846]
When people outside of HOT are setting up tasking managers, they often forget to remove (some of) its HOT *branding* (e.g. the favicon, descriptions, etc.). That can lead to confusion for the involved mappers and/or media reporting about it.

Here's two recent examples where groups inside the OSM community set up their own tasking manager instances: [mexico](http://52.41.11.193/osmtm/about), [italy](http://osmit-tm.wmflabs.org/) (where they have customized the templates by now). Some [media](https://www.gim-international.com/content/news/supporting-earthquake-emergency-operations-with-satellite-images) actually have mistaken the osmit-instance with the actual HOT one: *“Go to the Humanitarian OpenStreetMap Team (HOT) website http://osmit-tm.wmflabs.org/project/13”*

To solve this issue one could for the default case: make texts a bit more neutral by default, remove HOT contacts from pages where it's not clear that HOT isn't maintaining the instance (e.g. the footers), and not use the HOT-favicon in a default installation.

**Comment by althio** [comment]
duplicate of https://github.com/hotosm/osm-tasking-manager2/issues/840
follows https://github.com/hotosm/osm-tasking-manager2/pull/783

**Comment by tyrasd** [comment]
Oh, I didn't find those tickets earlier. Sorry for the dupe.
