### ISSUE TITLE
Allow adding specific imagery license

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager2#853]
so far it is only possible to choose within the existing drop-down list. Would be great to be able to put a specific one : one field for the title + another field to add the license text

**Comment by pgiraud** [comment]
Project managers already have the permissions to create new licenses.
http://tasks.dev.hotosm.org/license/new
Is it what you were looking for?

**Comment by severinmenard** [comment]
Yes, sorry I had missed it.
