### ISSUE TITLE
Wrong language in the title of the message sent when a completed task is rejected

### ISSUE THREAD

**Issue by Codain** [hotosm/osm-tasking-manager2#858]
Hi,

Two of my completed tasks has been rejected by users and I've received the email in the language of the user who has canceled the task. For instance I've received:

```
Aufgabe #25 als unvollständig markiert
Task #302 invalidated
```

My account is configured in French. Both comments that have been accociated in the reject was in English.

It would be better to send the messages in the language of the receiver and not of the sender.

Note that those messages was send in 5 monthes, so maybe the issue has been fixed.

**Comment by ethan-nelson** [comment]
Also see #321

**Comment by pgiraud** [comment]
Duplicate. Closing.
