### ISSUE TITLE
Don't let users validate a square they worked on

### ISSUE THREAD

**Issue by aawiseman** [hotosm/osm-tasking-manager2#909]
Or something like that -- I've seen in a few cases were new editors mapped and area then marked it as validated and left behind bad data.

Or (more complicated) only let more experienced or approved people validate their own squares.

**Comment by pgiraud** [comment]
This was addressed a while ago. https://github.com/hotosm/osm-tasking-manager2/pull/602
It looks like we're facing a regression somewhere.

**Comment by pgiraud** [comment]
This should be checked server-side as well. Sorry for my poor review on this pull request.

**Comment by smit1678** [comment]
I saw this working correctly on Friday at our workshop. New user tried to validate their own square but could not. @aawiseman did you happen to see this recently or replicate this?

**Comment by pgiraud** [comment]
@aawiseman FYI administrators or project managers can validate the tasks they worked on. Simple contributors don't.

**Comment by aawiseman** [comment]
Oh, my bad, I last saw it on the TeachOSM tasking manager. I do remember seeing it here though, but maybe that was before the code change? http://tasks.hotosm.org/project/1080

**Comment by bgirardot** [comment]
I think this is fixed. I will test and reopen if needed.. 

Thank you @aawiseman !
