### ISSUE TITLE
Login to Task Manager Redundancy

### ISSUE THREAD

**Issue by hpanno** [hotosm/osm-tasking-manager2#968]
When I navigate to the newly created Task Manager "Welcome, new user!" page I select 'log in', enter my credentials, select 'Grant Access' on the "Authorize access to my account" page, and then I am brought back to the "Welcome, new User!" page again. This loop persists where I would expect to see a new page after selecting "Grant Access" & a new project under the Projects section of my user profile.

I built this Task Manager using the directions here: https://github.com/hotosm/osm-tasking-manager2/wiki/Debian-installation

Operating System: OS X Yosemite 10.10.5
Browser: Chrome 55.0.2883.95
Please let me know if I can provide any additional information that would better help assess this issue. 
Thank you

**Comment by pgiraud** [comment]
Hi @hpanno 
Sorry for that. I found this bug too, and found a fix.
https://github.com/hotosm/osm-tasking-manager2/pull/965
Can you please test it and confirm that it solves your issue?

**Comment by hpanno** [comment]
@pgiraud thank you for your response. I was able to apply this change and it was a successful fix. 

Thank you for your help!
