### ISSUE TITLE
Users can't validate their own squares

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-tasking-manager2#971]
When validating squares, it should be a requirement that a second pair of eyes are checking the work.

**Comment by bgirardot** [comment]
hi @mataharimhairi Usually users can not validate their own tasks. They can review the work or invalidate of course, but not validate.

project managers and admins can validate their own tasks intentionally because they should know what is a valid task square or not.

**Comment by mataharimhairi** [comment]
Great! Thanks for correctly informing me. Probably to my own demise, I have had an admin account from the get go and haven't realised this. Good to know its already in place :)
