### ISSUE TITLE
Two minutes tutorials inside Learn section should be updated

### ISSUE THREAD

**Issue by fredychandra** [hotosm/osm-tasking-manager2#990]
Hi @bgirardot @TylerRadford 

The video inside Learn Section on New Tasking Manager should be updated. It is still using old tasking manager page as a reference (she the pic below). This should use the new TM page as well, so it will more sensible. I realize the video can be updated once the new TM is relased. 

![tm_learn](https://user-images.githubusercontent.com/6345285/27367448-4c6bd7d2-5677-11e7-88a0-36dfa3f121ea.JPG)

Cheers.

**Comment by pgiraud** [comment]
@fredychandra Can you please report this issue on the version 3 dedicated project instead?
See https://github.com/hotosm/tasking-manager

**Comment by fredychandra** [comment]
Hi @pgiraud  thank you for the notification. 
I will move it to the link above.

Cheers
