### ISSUE TITLE
New windows dialog to reaffirmed the completely task

### ISSUE THREAD

**Issue by samnawi** [hotosm/osm-tasking-manager2#991]
In the new tasking manager (http://tasks-demo.hotosm.org/), Should we need a new Windows dialog (after the user click "Mark as Completely Mapped") to affirm that task is really done? I think it important to prevent the new mapper or who still not familiar with the tasking manager tool, to click this button carelessly or some user accidentally click this button.
![tasking manager](https://user-images.githubusercontent.com/8871958/27369210-2534cdb8-5681-11e7-9b9a-6f614d5f7ac2.gif)

cc : @bgirardot @TylerRadford @fredychandra

**Comment by pgiraud** [comment]
@samnawi Can you please report this issue on the version 3 dedicated project instead?
See https://github.com/hotosm/tasking-manager

**Comment by samnawi** [comment]
Thank's @pgiraud for the information. My apologies about it. I will close this issue and move it to https://github.com/hotosm/tasking-manager
