### ISSUE TITLE
HOT Task Manager is not replying

### ISSUE THREAD

**Issue by verdy-p** [hotosm/osm-tasking-manager2#996]
I can't display any job in the task manager this morning 22 september 2017.
HOT TM server seems to be crashed or hangged

**Comment by smit1678** [comment]
To follow up here, TM was unresponsive for 21 minutes -- Timeout / Connection Refused from [StatusCake](https://uptime.statuscake.com/?TestID=syki6iogWX). 

Became responsive without any intervention. Let's reopen if this becomes an issue again today.
